
services:
  dotnet-test-service-dev:
    container_name: dotnet-test-service-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    environment:
      ASPNETCORE_URLS: "http://*:5000"
      MYSQL_CONNECTION_STRING: "Server=dotnet-test-mysql;Port=3306;Database=testdb;User Id=testdotnet;Password=testdotnet;Allow User Variables=true;Default Command Timeout=0;"
      JWT_SECRET_KEY: "6a449699-8c17-4f9b-afb7-7aa9ef475792"
      JWT_ISSUER: "test-user-jwt"
      JWT_AUDIENCE: "http://localhost:5000/"
    ports:
      - "5000:5000"
    networks:
      - dev-dotnet-test

  dotnet-test-backend-service:
    container_name: dotnet-test-backend-service
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.app
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    depends_on:
      - dotnet-test-mysql
      - dotnet-test-service-dev
    networks:
      - dev-dotnet-test
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_URLS: "http://*:8080"
      MYSQL_CONNECTION_STRING: "Server=dotnet-test-mysql;Port=3306;Database=testdb;User Id=testdotnet;Password=testdotnet;Allow User Variables=true;Default Command Timeout=0;"
      JWT_SECRET_KEY: "6a449699-8c17-4f9b-afb7-7aa9ef475792"
      JWT_ISSUER: "test-user-jwt"
      JWT_AUDIENCE: "http://localhost:5000/"

  dotnet-test-mysql:
    container_name: dotnet-test-mysql
    image: mysql:8.0
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: testdotnet
      MYSQL_DATABASE: testdb
      MYSQL_USER: testdotnet
      MYSQL_PASSWORD: testdotnet
    ports:
      - "33060:3306"
    networks:
      - dev-dotnet-test

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: dotnet-test-mysql
      MYSQL_ROOT_PASSWORD: testdotnet
    ports:
      - "8081:80"
    depends_on:
      - dotnet-test-mysql
    networks:
      - dev-dotnet-test

volumes:
  db_data:

networks:
  dev-dotnet-test:
    name: dev-dotnet-test
